# =========================
# GLOBAL SETTINGS
# =========================
BASEMNT="/srv/M"

# timeout for the smb server check
CHECK_TIMEOUT=1

# the max retry amount on first dis/connection
COUNT_MAX=3

# the wait in-between full rechecks
SLEEP=5

# delay between share mount/unmount actions (prevents spikes)
SPAWN_DELAY=0.1

# delay between server processing cycles (light throttling)
SERVER_DELAY=0.1

# mount options 
# gid=smbmount is a spcial group i set up so that i can allow any user the drive 
MOUNT_OPTIONS="uid=root,gid=smbmount,file_mode=0770,dir_mode=0770,soft"

# =========================
# SERVERS
# =========================
# FORMAT:
# name:ip:credentials_file
SERVERS=(
  "media-server:192.168.50.10:/etc/samba/media-smb-credentials"
  "backup-node:192.168.50.11:/etc/samba/backup-smb-credentials"
)

# =========================
# PATHS
# =========================
# FORMAT:
# label:mountpoint:remote_path:server_name
PATHS=(
  "mediaHome:${BASEMNT}/mediaHome:/home:media-server"
  "mediaData:${BASEMNT}/mediaData:/mnt:media-server"
  "mediaUSB:${BASEMNT}/mediaUSB:/usbs:media-server"

  "backupHome:${BASEMNT}/backupHome:/home:backup-node"
  "backupData:${BASEMNT}/backupData:/mnt:backup-node"
  "backupUSB:${BASEMNT}/backupUSB:/usbs:backup-node"
)
